version: '3.8'

services:
  app:
    build:
      context: ./StreamerApp
    environment:
      - FLASK_CONFIG=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SIGNALING_SERVER=signaling-server
      - VIDEO_SOURCE=${VIDEO_SOURCE}
      - AUDIO_SOURCE=${AUDIO_SOURCE}
    command: gunicorn -k gevent -w 1 -b 0.0.0.0:${FLASK_PORT} playerApp:app
    devices:
      - /dev/:/dev/
      - /dev/snb:/dev/snb
    volumes: 
      - /lib/modules:/lib/modules
    group_add:
      - video
      - audio
    privileged: true
    depends_on:
      - postgres
      - signaling-server
    networks:
      - webrtc-network
      - proxy-server
      - database

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - proxy-server

  signaling-server:
    build:
      context: ./signalling-server
    ports: 
      - "8443:8443"
    environment:
      - WEBRTCSINK_SIGNALLING_SERVER_LOG=info
    networks:
      - webrtc-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    networks:
      - database

networks:
  webrtc-network:
    driver: bridge
  database:
    driver: bridge
  proxy-server:
    driver: bridge